// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACHWxwKTPz3huQJ8_ah3NC2Er6n77fJbU',
    appId: '1:807299698302:web:f5f20c674b390f640a522f',
    messagingSenderId: '807299698302',
    projectId: 'cloudmsg-14ab9',
    authDomain: 'cloudmsg-14ab9.firebaseapp.com',
    storageBucket: 'cloudmsg-14ab9.firebasestorage.app',
    measurementId: 'G-F9Y1S4489J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY1_W2oFcnJpD9vf6TEbNP6wEaGgBPEeY',
    appId: '1:807299698302:android:4e6c580f2b24017d0a522f',
    messagingSenderId: '807299698302',
    projectId: 'cloudmsg-14ab9',
    storageBucket: 'cloudmsg-14ab9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByZpbPywlXOl2EZ3CddsEA7kagcGne9TM',
    appId: '1:807299698302:ios:2f1b1c4954880d0e0a522f',
    messagingSenderId: '807299698302',
    projectId: 'cloudmsg-14ab9',
    storageBucket: 'cloudmsg-14ab9.firebasestorage.app',
    iosBundleId: 'com.example.cloudmsg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByZpbPywlXOl2EZ3CddsEA7kagcGne9TM',
    appId: '1:807299698302:ios:2f1b1c4954880d0e0a522f',
    messagingSenderId: '807299698302',
    projectId: 'cloudmsg-14ab9',
    storageBucket: 'cloudmsg-14ab9.firebasestorage.app',
    iosBundleId: 'com.example.cloudmsg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACHWxwKTPz3huQJ8_ah3NC2Er6n77fJbU',
    appId: '1:807299698302:web:e7b4a1662c08c6ad0a522f',
    messagingSenderId: '807299698302',
    projectId: 'cloudmsg-14ab9',
    authDomain: 'cloudmsg-14ab9.firebaseapp.com',
    storageBucket: 'cloudmsg-14ab9.firebasestorage.app',
    measurementId: 'G-0RM6PKWNHB',
  );
}
